### ISSUE TITLE
directory or path error

### ISSUE THREAD

**Issue by chirutheboss** [sanjit-sinha/Tg-MediaInfoBot#21]
[ ERROR] - TelegramBot.plugins.mediainfo - [Errno 2] No such file or directory

**Comment by sanjit-sinha** [comment]
Need more information about that error.

**Comment by chirutheboss** [comment]
> Need more information about that error.

When i try to get screenshot or mediainfo i get this error as there's no directory of screenshot in plugins folder ....

**Comment by sanjit-sinha** [comment]
This happen everytime? If yes then try to redeploy it

**Comment by chirutheboss** [comment]
> This happen everytime? If yes then try to redeploy it

Yes for every file or link it happens when try to get ss or mediainfo

**Comment by sanjit-sinha** [comment]
Redeploy.

**Comment by chirutheboss** [comment]
> Redeploy.

Bro i redeploy but getting same error no such file or directory  (TelegramBot.plugins.mediainfo) btw i deployed in heroku by creating procfile and runtime.txt i didn't edit anything i just created those files for deployment in heroku

**Comment by sanjit-sinha** [comment]
No idea about heroku then. It work fine in vps.

**Comment by chirutheboss** [comment]
> No idea about heroku then. It work fine in vps.

Atleast help me bro i put some effort to deploy it on heroku 🥲🥲

**Comment by sanjit-sinha** [comment]
I have no idea about heroku. Sry
