### ISSUE TITLE
sox spectogram

### ISSUE THREAD

**Issue by alamia442** [sanjit-sinha/Tg-MediaInfoBot#25]
can you update spek with sox using this script
check last answer
https://unix.stackexchange.com/questions/200168/how-to-create-the-spectrogram-of-many-audio-files-efficiently-with-sox

**Comment by sanjit-sinha** [comment]
Why, though? Does that script provide something better than the current script?

**Comment by alamia442** [comment]
some time failed generate spektogram
https://graph.org//file/db0ea3ba5392c0fba2f60.png
https://i.ibb.co/TR5KVwK/Jepretan-Layar-2023-06-08-pukul-11-49-27.png

**Comment by sanjit-sinha** [comment]
Can you provide me that audio in which you get errors?
